version: "3.1"

services:
  cron-1:
    image: debian:stable-slim
    environment:
      ADDR: "0.0.0.0"
      PORT: "65056"
      RUST_BACKTRACE: 1
    volumes:
      - ./target/release/examples/base:/usr/bin/escalon-jobs
    command: [ "escalon-jobs" ]
    deploy:
      replicas: 4
